# Yarn 4.9.2 Configuration

# Enable node-modules linker for better compatibility with tools that expect node_modules
nodeLinker: node-modules

# Enable global cache to improve performance
enableGlobalCache: true

# Enable immutable installs in CI environments
enableImmutableInstalls: false

# Network settings
httpTimeout: 60000

# Enable telemetry (set to false if you prefer to opt out)
enableTelemetry: false

# Compression level for the cache
compressionLevel: mixed

# Package extensions (useful for patching packages if needed)
packageExtensions: {}